/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/photos/': RouteRecordInfo<'/photos/', '/photos', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/2024final': RouteRecordInfo<'/posts/2024final', '/posts/2024final', Record<never, never>, Record<never, never>>,
    '/posts/2025final': RouteRecordInfo<'/posts/2025final', '/posts/2025final', Record<never, never>, Record<never, never>>,
    '/posts/cherry-knowledge': RouteRecordInfo<'/posts/cherry-knowledge', '/posts/cherry-knowledge', Record<never, never>, Record<never, never>>,
    '/posts/cherry-knowledge-v2': RouteRecordInfo<'/posts/cherry-knowledge-v2', '/posts/cherry-knowledge-v2', Record<never, never>, Record<never, never>>,
    '/posts/cherry-rag-websearch': RouteRecordInfo<'/posts/cherry-rag-websearch', '/posts/cherry-rag-websearch', Record<never, never>, Record<never, never>>,
    '/posts/claas-software-2024': RouteRecordInfo<'/posts/claas-software-2024', '/posts/claas-software-2024', Record<never, never>, Record<never, never>>,
    '/posts/comfyui-furry': RouteRecordInfo<'/posts/comfyui-furry', '/posts/comfyui-furry', Record<never, never>, Record<never, never>>,
    '/posts/csharp-event-and-delegate': RouteRecordInfo<'/posts/csharp-event-and-delegate', '/posts/csharp-event-and-delegate', Record<never, never>, Record<never, never>>,
    '/posts/efcore-migration': RouteRecordInfo<'/posts/efcore-migration', '/posts/efcore-migration', Record<never, never>, Record<never, never>>,
    '/posts/macos-software': RouteRecordInfo<'/posts/macos-software', '/posts/macos-software', Record<never, never>, Record<never, never>>,
    '/posts/mcp': RouteRecordInfo<'/posts/mcp', '/posts/mcp', Record<never, never>, Record<never, never>>,
    '/posts/mcp-arxiv': RouteRecordInfo<'/posts/mcp-arxiv', '/posts/mcp-arxiv', Record<never, never>, Record<never, never>>,
    '/posts/net-json-convenient': RouteRecordInfo<'/posts/net-json-convenient', '/posts/net-json-convenient', Record<never, never>, Record<never, never>>,
    '/posts/nvim-shortcuts': RouteRecordInfo<'/posts/nvim-shortcuts', '/posts/nvim-shortcuts', Record<never, never>, Record<never, never>>,
    '/posts/podwise-ai': RouteRecordInfo<'/posts/podwise-ai', '/posts/podwise-ai', Record<never, never>, Record<never, never>>,
    '/posts/rag': RouteRecordInfo<'/posts/rag', '/posts/rag', Record<never, never>, Record<never, never>>,
    '/posts/rust-in-depth-1': RouteRecordInfo<'/posts/rust-in-depth-1', '/posts/rust-in-depth-1', Record<never, never>, Record<never, never>>,
    '/posts/rust-in-depth-2': RouteRecordInfo<'/posts/rust-in-depth-2', '/posts/rust-in-depth-2', Record<never, never>, Record<never, never>>,
    '/posts/subtitle-translator-cli': RouteRecordInfo<'/posts/subtitle-translator-cli', '/posts/subtitle-translator-cli', Record<never, never>, Record<never, never>>,
    '/posts/yazi': RouteRecordInfo<'/posts/yazi', '/posts/yazi', Record<never, never>, Record<never, never>>,
    '/posts/zero2rust': RouteRecordInfo<'/posts/zero2rust', '/posts/zero2rust', Record<never, never>, Record<never, never>>,
    '/private/README': RouteRecordInfo<'/private/README', '/private/README', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/test/': RouteRecordInfo<'/test/', '/test', Record<never, never>, Record<never, never>>,
  }
}
