/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/collections': RouteRecordInfo<'/collections', '/collections', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/diaries/2026-03-11-peanut-birthday': RouteRecordInfo<'/diaries/2026-03-11-peanut-birthday', '/diaries/2026-03-11-peanut-birthday', Record<never, never>, Record<never, never>>,
    '/diaries/2026-03-12-ticket-to-the-future': RouteRecordInfo<'/diaries/2026-03-12-ticket-to-the-future', '/diaries/2026-03-12-ticket-to-the-future', Record<never, never>, Record<never, never>>,
    '/diaries/2026-03-13-night-direction': RouteRecordInfo<'/diaries/2026-03-13-night-direction', '/diaries/2026-03-13-night-direction', Record<never, never>, Record<never, never>>,
    '/diaries/2026-03-14-night-of-order-and-motion': RouteRecordInfo<'/diaries/2026-03-14-night-of-order-and-motion', '/diaries/2026-03-14-night-of-order-and-motion', Record<never, never>, Record<never, never>>,
    '/diaries/2026-03-15-not-rushing-to-finish-tonight': RouteRecordInfo<'/diaries/2026-03-15-not-rushing-to-finish-tonight', '/diaries/2026-03-15-not-rushing-to-finish-tonight', Record<never, never>, Record<never, never>>,
    '/diaries/2026-04-15-a-day-made-of-small-actions': RouteRecordInfo<'/diaries/2026-04-15-a-day-made-of-small-actions', '/diaries/2026-04-15-a-day-made-of-small-actions', Record<never, never>, Record<never, never>>,
    '/diary': RouteRecordInfo<'/diary', '/diary', Record<never, never>, Record<never, never>>,
    '/friendship': RouteRecordInfo<'/friendship', '/friendship', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/photos/': RouteRecordInfo<'/photos/', '/photos', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/2024final': RouteRecordInfo<'/posts/2024final', '/posts/1001', Record<never, never>, Record<never, never>>,
    '/posts/2025final': RouteRecordInfo<'/posts/2025final', '/posts/1002', Record<never, never>, Record<never, never>>,
    '/posts/cherry-knowledge': RouteRecordInfo<'/posts/cherry-knowledge', '/posts/1003', Record<never, never>, Record<never, never>>,
    '/posts/cherry-knowledge-v2': RouteRecordInfo<'/posts/cherry-knowledge-v2', '/posts/1004', Record<never, never>, Record<never, never>>,
    '/posts/cherry-rag-websearch': RouteRecordInfo<'/posts/cherry-rag-websearch', '/posts/1005', Record<never, never>, Record<never, never>>,
    '/posts/claas-software-2024': RouteRecordInfo<'/posts/claas-software-2024', '/posts/1006', Record<never, never>, Record<never, never>>,
    '/posts/comfyui-furry': RouteRecordInfo<'/posts/comfyui-furry', '/posts/1007', Record<never, never>, Record<never, never>>,
    '/posts/csharp-event-and-delegate': RouteRecordInfo<'/posts/csharp-event-and-delegate', '/posts/1008', Record<never, never>, Record<never, never>>,
    '/posts/efcore-migration': RouteRecordInfo<'/posts/efcore-migration', '/posts/1009', Record<never, never>, Record<never, never>>,
    '/posts/macos-software': RouteRecordInfo<'/posts/macos-software', '/posts/1010', Record<never, never>, Record<never, never>>,
    '/posts/mcp-arxiv': RouteRecordInfo<'/posts/mcp-arxiv', '/posts/1011', Record<never, never>, Record<never, never>>,
    '/posts/mcp': RouteRecordInfo<'/posts/mcp', '/posts/1012', Record<never, never>, Record<never, never>>,
    '/posts/net-json-convenient': RouteRecordInfo<'/posts/net-json-convenient', '/posts/1013', Record<never, never>, Record<never, never>>,
    '/posts/nvim-shortcuts': RouteRecordInfo<'/posts/nvim-shortcuts', '/posts/1014', Record<never, never>, Record<never, never>>,
    '/posts/podwise-ai': RouteRecordInfo<'/posts/podwise-ai', '/posts/1015', Record<never, never>, Record<never, never>>,
    '/posts/rag': RouteRecordInfo<'/posts/rag', '/posts/1016', Record<never, never>, Record<never, never>>,
    '/posts/rust-in-depth-1': RouteRecordInfo<'/posts/rust-in-depth-1', '/posts/1017', Record<never, never>, Record<never, never>>,
    '/posts/rust-in-depth-2': RouteRecordInfo<'/posts/rust-in-depth-2', '/posts/1018', Record<never, never>, Record<never, never>>,
    '/posts/start-of-2026': RouteRecordInfo<'/posts/start-of-2026', '/posts/1019', Record<never, never>, Record<never, never>>,
    '/posts/subtitle-translator-cli': RouteRecordInfo<'/posts/subtitle-translator-cli', '/posts/1020', Record<never, never>, Record<never, never>>,
    '/posts/yazi': RouteRecordInfo<'/posts/yazi', '/posts/1021', Record<never, never>, Record<never, never>>,
    '/posts/zero2rust': RouteRecordInfo<'/posts/zero2rust', '/posts/1022', Record<never, never>, Record<never, never>>,
    '/private/README': RouteRecordInfo<'/private/README', '/private/README', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/test/': RouteRecordInfo<'/test/', '/test', Record<never, never>, Record<never, never>>,
  }
}
